#!/usr/bin/env bash
#
# cdtempl bootstrap - generate BOOTSTRAP-CD.md, the document that hands a design
# system to a Claude Design project
#
# ONE GENERATOR, TWO OUTPUTS, AND THAT IS THE WHOLE DESIGN. Run over an empty
# target it emits the instructions a COLD Claude Design project needs to build a
# design system from nothing. Run over a populated target it emits everything a
# fresh Claude Design project needs to RESUME from where the last one stopped.
# Same command, same document, content following the tree's state.
#
# Built as two documents they would drift, and hand-authored drift is already the
# recorded defect against `cdtempl brief` three times over -- it cannot express a
# repackaging round, cannot order a slug the library does not hold, and carried
# no numbering high-water marks until 30 July 2026. Four hand-written briefs on
# 29 July are the evidence for what that costs.
#
# WHY IT EXISTS AT ALL, WHICH IS NOT THE OBVIOUS REASON. Bootstrap is an
# INVARIANT before it is a workflow. `design/system/` is the single source of
# truth for a project's design system; Claude Design is a clamp-on tool used to
# work on it. That claim is only worth anything if it can be tested, and this is
# the test: if a cold Claude Design project can be reconstructed from the tree
# alone, then nothing important is hiding in a chat log. The normal working
# relationship stays a long-running Claude Design project synced each round --
# this is the guarantee underneath it, not the routine.
#
# SO IT IS REGENERATED BY EVERY SYNC rather than by a command someone remembers
# to run. Its USE is rare; its CURRENCY has to be continuous, because an
# unexercised guarantee is a claim. This project has shipped bugs whose synthetic
# fixtures agreed with every one of them, and found them only by running against
# the real thing.
#
# IT CARRIES EVERYTHING IT NEEDS, for the same reason `cdtempl brief` does: Claude
# Design is scoped to one directory and cannot read this repository. A pointer to
# a file the reader cannot open is a hole in the document, not a reference.
#

# The numbering high-water marks are `brief`'s, and there is only one correct
# answer to "what is the last id in use", so this reuses that section rather than
# growing a second scanner. The one already here reads BOTH naming conventions --
# `ADR-0003 ...` and `adr0001-...` -- because a scan that saw only the first
# reported a project with 33 ADRs as having none, and that bug appeared inside
# the fix for itself. A second copy would not inherit the lesson.
if ! declare -F brief_numbering >/dev/null 2>&1; then
  # shellcheck source=/dev/null
  source "$CDTEMPL_HOME/lib/cmd_brief.sh"
fi

cmd_bootstrap() {
  local to_stdout=0
  local flag_target=""
  local mode="adopt"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --stdout)
        to_stdout=1
        shift
        ;;
      --delta)
        mode="delta"
        shift
        ;;
      --target)
        if [[ $# -lt 2 ]]; then
          error "--target needs a path"
          return 2
        fi
        flag_target="$2"
        shift 2
        ;;
      -h|--help)
        show_help bootstrap
        return 0
        ;;
      -*)
        error "unknown option: $1"
        echo "usage: cdtempl bootstrap [--delta] [--stdout] [--target PATH]" >&2
        return 2
        ;;
      *)
        error "bootstrap takes no positional arguments: $1"
        return 2
        ;;
    esac
  done

  local target source
  target="$(resolve_target "$flag_target" "$PWD")" || return 2
  source="$(target_source "$flag_target" "$PWD")" || return 2

  if [[ ! -d "$target" ]]; then
    error "target does not exist: $target"
    echo "  run 'cdtempl new <name>' to scaffold one, or pass --target" >&2
    return 1
  fi

  local body
  if [[ "$mode" == "delta" ]]; then
    body="$(compose_delta "$target")" || return 1
  else
    body="$(compose_bootstrap "$target" "$source")" || return 1
  fi

  if [[ "$to_stdout" == "1" ]]; then
    printf '%s\n' "$body"
    return 0
  fi

  local dest
  if [[ "$mode" == "delta" ]]; then
    dest="$target/RETURN-DELTA.md"
  else
    dest="$target/BOOTSTRAP-CD.md"
  fi

  printf '%s\n' "$body" | atomic_write "$dest" || return 1
  success "wrote $dest"

  return 0
}

# Regenerate BOOTSTRAP-CD.md quietly, for the install and import paths to call.
#
# The currency argument above is only true if every sync rewrites it, so this is
# the seam both install paths hang it on. It reports rather than fails: a sync
# that landed a drop correctly has done the dangerous part, and refusing at the
# very end over a regenerated document would leave the tree correct and the
# command red.
#
# THE SEAM ONLY CATCHES SYNCS. A repo-side edit has no install to hang this on,
# and retiring an addendum is exactly that: Baize's document quoted two retired
# addenda for five hours on 31 July, and would have handed Claude Design two
# closed gaps to close again. Nothing here detects that -- it is a hand step
# after touching `addenda/` until something makes it one.
bootstrap_refresh() {
  local target="$1"
  local source="${2:-}"
  local body

  if ! body="$(compose_bootstrap "$target" "$source")"; then
    warn "could not regenerate BOOTSTRAP-CD.md -- run 'cdtempl bootstrap' by hand"
    return 0
  fi

  if ! printf '%s\n' "$body" | atomic_write "$target/BOOTSTRAP-CD.md"; then
    warn "could not write BOOTSTRAP-CD.md -- run 'cdtempl bootstrap' by hand"
    return 0
  fi

  info "regenerated BOOTSTRAP-CD.md"
  return 0
}

# ============================================================================
# COMPOSITION
# ============================================================================

compose_bootstrap() {
  local target="$1"
  local source="${2:-}"
  local state count

  state="$(bootstrap_state "$target")"

  # Counted once and passed down. The inventory needs it to decide whether to
  # print the asset table, and the contract needs it to decide whether it is
  # describing this tree's shape or a shape it does not have -- which are the
  # same question and must not be answered twice.
  count="$(each_drop_asset "$target" | grep -c . || true)"

  bootstrap_header "$target" "$source" "$state"
  bootstrap_what_this_is
  bootstrap_inventory "$target" "$state" "$count"
  bootstrap_borrowed "$target"
  bootstrap_contract "$target" "$state"
  bootstrap_versions "$target"
  bootstrap_classification
  brief_numbering "$target"
  bootstrap_addenda "$target"
  bootstrap_next "$state" "$target"

  return 0
}

# ============================================================================
# WHAT THE SCANS AGREE TO IGNORE
# ============================================================================
#
# ONE DEFINITION EACH, because this file used to carry three skip lists that
# disagreed, and the disagreement was the defect. `bootstrap_state` considered
# dotfiles, `bootstrap_unclassified` did not, and the file counter excluded
# nothing at all -- so a tree could be called warm on the strength of a file the
# inventory then never mentioned.

# Noise: never content, never listed, never counted, in any scan here.
bootstrap_is_noise() {
  case "$1" in
    .DS_Store|.git) return 0 ;;
  esac
  return 1
}

# Already reported by a section of its own, so listing it again double-reports
# rather than informs.
#
# `assets` is CONDITIONAL and that is the whole point of this predicate. The
# asset table above covers `assets/` only when `each_drop_asset` found something
# in it -- and that walker looks for SUBDIRECTORIES, `assets/<slug>/`. Three of
# the four real projects keep flat files there instead: Baize 7, snorkeltoast 4,
# and Gyre & Gymble is the only one in the walker's shape. So an unconditional
# skip meant the table reported nothing, this list reported nothing, and seven
# tracked files -- a logo and an app icon among them -- appeared NOWHERE in a
# document that then says "export every path listed here". Claude Design obeying
# it would have omitted them, and the install would have removed them.
#
# The dangerous direction again, and worse than the usual form: the wrong
# verdict is not printed to a terminal someone might read, it is AUTHORED INTO
# THE DOCUMENT handed to the other side.
bootstrap_is_reported() {
  local name="$1"
  local asset_count="$2"

  # A refused file is not returnable material, so listing it under "all of it
  # comes back" asks Claude Design for something the install then discards. The
  # contract section names it as not theirs instead, the way `addenda/` is.
  # Read from CDTEMPL_DROP_REFUSED_FILES rather than restated, so the inbound
  # refusal and the outbound instruction cannot drift apart.
  if drop_file_is_refused "$name"; then
    return 0
  fi

  case "$name" in
    addenda|_inbox) return 0 ;;
    BOOTSTRAP-CD.md|RETURN-DELTA.md) return 0 ;;
    index.md) return 0 ;;
    assets) [[ "$asset_count" -gt 0 ]] && return 0 ;;
  esac

  return 1
}

# Files under a path, counting the deliverable rather than the disk.
bootstrap_count_files() {
  find "$1" -type f ! -name '.DS_Store' ! -path '*/.git/*' 2>/dev/null | grep -c . || true
}

# cold or warm, decided by what is actually in the tree rather than by a flag.
#
# A flag would let the caller assert a state the tree contradicts, and the two
# documents this produces differ in what they can safely assume. Measured, not
# declared -- the same reason `blanks` is computed.
#
# DECIDED ON ANY CONTENT, NOT ON assets/, and that distinction is the whole
# lesson of this project restated. An earlier version asked `each_drop_asset` and
# called a tree cold when it found none -- which over Lamplight, 708 tracked
# files and 1.1GB of delivered design system, would have reported a COLD START
# and told Claude Design to build from nothing. As-is exports are not in the
# Cdtempl asset shape; `check` refuses three of the four for exactly that reason.
# A probe that sees one corner must not return a verdict on the whole tree, and
# the dangerous direction is always the one that reports absence.
bootstrap_state() {
  local target="$1"
  local entry name

  for entry in "$target"/* "$target"/.[!.]*; do
    [[ -e "$entry" ]] || continue
    name="$(basename "$entry")"
    bootstrap_is_noise "$name" && continue
    # cdtempl.json is Cdtempl-side material like this document itself: `new` and
    # `init` both write it at the tree root, so counting it as content would
    # make every freshly scaffolded tree measure warm and the cold document
    # unreachable again -- the exact defect the skeleton clause below fixed.
    case "$name" in
      _inbox|BOOTSTRAP-CD.md|RETURN-DELTA.md|cdtempl.json) continue ;;
    esac

    # AN EMPTY SKELETON DIRECTORY IS NOT CONTENT, and missing that made the
    # cold document unreachable through the tool's own commands. `new` and
    # `init` both create assets/, kit/ and notes/ with a .gitkeep apiece, so
    # every freshly scaffolded tree measured warm -- and `cdtempl new acme &&
    # cdtempl bootstrap` told Claude Design "the design system already exists,
    # do not start it again" over three empty directories. The only way to get
    # the cold document was to point bootstrap at a tree with no skeleton,
    # which it refuses as non-existent. An unexercised guarantee is a claim,
    # and this one had quietly stopped being reachable at all.
    #
    # This does NOT walk back to the each_drop_asset bug the comment above
    # describes. That one asked whether the tree held Cdtempl-SHAPED assets and
    # called Lamplight cold because its 708 files are not in that shape. This
    # asks only whether a directory holds anything at all, so any file of any
    # shape still reads as warm.
    if [[ -d "$entry" ]]; then
      local inner inner_name has_content=0
      for inner in "$entry"/* "$entry"/.[!.]*; do
        [[ -e "$inner" ]] || continue
        inner_name="$(basename "$inner")"
        [[ "$inner_name" == ".gitkeep" ]] && continue
        bootstrap_is_noise "$inner_name" && continue
        has_content=1
        break
      done
      [[ "$has_content" -eq 0 ]] && continue
    fi

    echo "warm"
    return 0
  done

  echo "cold"
  return 0
}

bootstrap_header() {
  local target="$1"
  local source="$2"
  local state="$3"

  echo "# Bootstrap: adopting this design system"
  echo ""
  echo "**For a Claude Design project taking on the design system held at \`design/system/\`.**"
  echo "Generated by \`cdtempl bootstrap\` from the tree itself, so it describes what is"
  echo "actually there rather than what anyone remembers being there."
  echo ""
  echo "**This document is self-contained.** You cannot read the repository it came from,"
  echo "so nothing here points at a file you cannot open. If something looks like it is"
  echo "missing, it is missing, and saying so is more useful than inferring it."
  echo ""

  if [[ "$state" == "cold" ]]; then
    echo "**The tree is empty. This is a cold start** -- you are building the design system,"
    echo "not resuming one."
  else
    echo "**The tree is populated. This is a resume** -- the design system already exists and"
    echo "you are picking it up. Do not start it again."
  fi

  echo ""

  if [[ -n "$source" ]]; then
    echo "Target resolved from: \`$source\`"
    echo ""
  fi

  return 0
}

bootstrap_what_this_is() {
  cat <<'EOF'
## The one thing to understand before anything else

**This tree is the single source of truth for the design system. You are a tool
that works on it.**

That is the opposite of how design tooling usually assumes it works, and it is
deliberate. While the authoritative copy lived inside a Claude Design project,
the source of truth sat somewhere that could not be diffed, reviewed or
reverted -- and every failure this programme has had traces to that one fact.
Corrections had to be carried into a chat by hand and hoped for. A delivery
could be *ahead* of its repository as easily as behind it. Identifiers were
allocated blind and a collision cost a full export cycle on both sides.

So: the repository holds the truth, you work on it, and what you export replaces
what is there. Three consequences worth stating plainly.

**Corrections land at source.** If something is wrong, fix it in the material
you export, never only in a delivery note. A fix that lives only in a note is
reverted by your next export.

**Never allocate an identifier blind.** The high-water marks are below. If you
need an ADR, steel thread or work package number and this document does not give
you one, ask rather than assume.

**What the receiving project builds from this is entirely its own business.** It
takes this tree as requirements and implements it in its own technology at its
own pace. A gap between this tree and that application is expected and is never
a defect. Nothing you write here runs anywhere.

EOF
  return 0
}

bootstrap_inventory() {
  local target="$1"
  local state="$2"
  local count="$3"
  local slug

  echo "## What is in the tree right now"
  echo ""

  if [[ "$state" == "cold" ]]; then
    echo "**Nothing.** No assets exist. Everything below describes the shape to build into."
    echo ""
    return 0
  fi

  if [[ "$count" -gt 0 ]]; then
    echo "**$count assets** in the Cdtempl asset shape, at \`assets/\`. Each is authoritative --"
    echo "it is the current state of that piece of the design system, not a draft of it."
    echo ""
    echo "| Asset | Spec |"
    echo "| ----- | ---- |"

    while IFS= read -r slug; do
      [[ -z "$slug" ]] && continue
      if [[ -f "$target/assets/$slug/spec.md" ]]; then
        echo "| \`$slug\` | present |"
      else
        echo "| \`$slug\` | **absent** |"
      fi
    done < <(each_drop_asset "$target")

    echo ""
  fi

  # Everything else at the top level, named rather than summarised.
  #
  # THE ASSET COUNT IS NOT A DESCRIPTION OF THE TREE. An as-is export is not in
  # the Cdtempl shape -- Lamplight carries 708 files across design-system/, docs/,
  # handoff/, prototypes/ and venture/, of which four are assets. Printing "4
  # assets" and stopping tells Claude Design the tree holds four things, and it
  # would then export four things. Whatever this cannot classify, it lists.
  bootstrap_unclassified "$target" "$count"

  if [[ -f "$target/index.md" ]]; then
    echo "\`index.md\` is present and is the manifest: every asset, its status, its spec version."
  else
    echo "**\`index.md\` is absent.** There is no manifest, so nothing here can tell you whether"
    echo "an asset is complete or merely present. Producing one is part of the next round."
  fi

  echo ""
  return 0
}

# Every top-level entry not already reported by a section of its own, by name.
#
# Silence here would be the failure this project keeps rediscovering: a report
# that covers what it understood and says nothing about the rest reads as
# complete. So the rule is inverted -- everything is listed unless something
# else in this document already accounts for it, and `bootstrap_is_reported`
# holds that one exception list.
#
# DOTFILES ARE SCANNED, matching `bootstrap_state`. `.thumbnail` is tracked in
# three of the four real projects and was invisible here, so an export that
# dropped it would have had the install remove it with nothing to warn anyone.
bootstrap_unclassified() {
  local target="$1"
  local asset_count="$2"
  local entry name found=0

  # SORTED HERE RATHER THAN LEFT TO THE GLOB. `export LC_COLLATE=C` in the
  # dispatcher fixed this for every locale that sets LC_COLLATE, and the macOS
  # CI runner then proved the documented residual real: LC_ALL overrides
  # LC_COLLATE per POSIX, so an environment that sets LC_ALL reordered this
  # listing again and the ordering test failed on that runner alone.
  #
  # An environment variable was the wrong place for it. This is the listing that
  # has to be deterministic, so it sorts itself, and no caller's environment can
  # reach it.
  while IFS= read -r entry; do
    [[ -e "$entry" ]] || continue
    name="$(basename "$entry")"
    bootstrap_is_noise "$name" && continue
    bootstrap_is_reported "$name" "$asset_count" && continue
    if [[ "$found" -eq 0 ]]; then
      echo "### The rest of the tree"
      echo ""
      if [[ "$asset_count" -gt 0 ]]; then
        echo "**The asset list above is not the whole tree.** These top-level paths are here too,"
        echo "and they come back with it:"
      else
        echo "**There are no assets in the Cdtempl shape, and the tree is not empty.** This is an"
        echo "as-is export rather than a converted drop. These top-level paths are what it holds:"
      fi
      echo ""
      found=1
    fi
    if [[ -d "$entry" ]]; then
      echo "- \`$name/\` -- $(bootstrap_count_files "$entry") files"
    else
      echo "- \`$name\`"
    fi
  done < <(
    for entry in "$target"/* "$target"/.[!.]*; do
      [[ -e "$entry" ]] && printf '%s\n' "$entry"
    done | LC_ALL=C sort
  )

  if [[ "$found" -eq 1 ]]; then
    echo ""
    echo "**All of it is yours and all of it comes back.** Cdtempl stores the whole deliverable,"
    echo "so export every path listed here along with the assets. Anything you leave out of the"
    echo "archive reads as a deletion on the receiving side."
    echo ""
  fi

  return 0
}

# WHICH SHAPE TO DESCRIBE, and getting this wrong nearly cost a tree.
#
# This used to print the Cdtempl contract shape unconditionally, opening with
# "Cdtempl owns exactly these paths under the target. What you export is unpacked
# into them". Over an as-is tree -- Baize's 442 files across docs/, handoff/,
# tiles/, uploads/ -- that reads as an instruction to restructure. Baize's
# Claude Design project read it exactly that way on 31 July, worked out that
# converting would break every relative pointer in the tree, and refused. It was
# right, and a less careful reader would have done it.
#
# A document describing a shape the tree does not have, in a section headed
# "the shape to export", is not a reference -- it is an order.
# A DIRECTORY CALLED assets/ IS NOT THE CDTEMPL SHAPE, and this predicate exists
# because the first version of the branch below asked exactly that.
#
# Lamplight has `assets/` holding four subdirectories -- brand, portraits, ref,
# shots -- and not one of them carries a `spec.md`. It is an as-is tree using a
# name the drop contract happens to own, which is a standing hazard here: three
# of the four projects use `assets/` for something that is not a Cdtempl asset.
# Asking "are there asset directories" put Lamplight on the shaped branch and
# handed it the restructure order this whole change exists to stop.
#
# So the question is whether the tree holds an asset in the CONTRACT's shape,
# and the contract's own marker for that is the spec. Gyre & Gymble: 16 of 16.
# Everyone else: none.
bootstrap_is_cdtempl_shaped() {
  local target="$1"
  local slug

  while IFS= read -r slug; do
    [[ -z "$slug" ]] && continue
    [[ -f "$target/assets/$slug/spec.md" ]] && return 0
  done < <(each_drop_asset "$target")

  return 1
}

# A copy of the PROJECT's own documents, sitting inside the drop.
#
# The mirror image of `docs/design/` -- that was a copy of the drop landed in
# the repository, this is a copy of the repository landed in the drop, and it
# goes stale by the same mechanism. Both app projects carry one: Baize 28 files
# mirroring its `intent/st/`, Lamplight 58.
#
# They are there for a good reason -- a steel thread's acceptance criteria are
# what a round is answering -- and THE REASON EXPIRES WITH THE ROUND. Baize's
# had already drifted in two dimensions by 31 July: `ST0016/acceptance.md` was
# 129 lines in the repository and 237 in the mirror, and nine of the 28 sat at
# paths the repository had since moved under `NOT-STARTED/`. Not a duplicate --
# a second and differently-wrong answer to what ST0016 requires.
#
# Detected by Intent's own layout, an `intent/` directory holding `st/`, because
# a design system has no reason to contain one and a guess with a wider net
# would start naming real deliverables.
bootstrap_borrowed() {
  local target="$1"
  local dir rel count found=0

  while IFS= read -r dir; do
    [[ -z "$dir" ]] && continue
    [[ -d "$dir/st" ]] || continue
    if [[ "$found" -eq 0 ]]; then
      echo "## Borrowed from the project, and due back"
      echo ""
      echo "This tree carries material whose home is the project's own \`intent/\` directory --"
      echo "steel threads, work packages, acceptance criteria. Either you were given it so you"
      echo "could read what a round was answering, or you drafted it for them. **Either way it"
      echo "does not live here.**"
      echo ""
      found=1
    fi
    rel="${dir#"$target"/}"
    count="$(bootstrap_count_files "$dir")"
    echo "- \`$rel/\` -- $count files"
  done < <(find "$target" -type d -name intent 2>/dev/null | sort)

  if [[ "$found" -eq 1 ]]; then
    cat <<'EOF'

**Retire it once the project has taken it. It must not survive more than one round.**

You can read this project's repository directly, so you do not need a copy in order to see
these documents -- and a copy you keep is one that drifts. It drifts in both directions at
once, which is what makes it worse than a duplicate: the project edits its copy and you edit
yours, so the two disagree on content; and when the project moves a document, yours stays at
the old path. A stale second answer to "what does this require" is more dangerous than no
answer, because it looks like an answer.

**Say in `RETURN.md`, file by file, what you changed or authored here.** The receiving side
has to carry it across by hand -- installing the drop updates your copy and never theirs,
so anything you do not name is lost.
EOF
    echo ""
  fi

  return 0
}

bootstrap_contract() {
  local target="$1"
  local state="${2:-warm}"

  # A COLD TREE HAS NO SHAPE, so asking whether it holds Cdtempl-shaped assets
  # returns the absence answer and selects the as-is contract -- which told a
  # project building from nothing "this document is not asking you to adopt"
  # the very shape `cdtempl check` then requires of it. The two documents
  # disagreed, and the one Claude Design reads first would have won.
  #
  # The as-is contract exists for a tree that ARRIVED in some other shape and
  # must not be restructured under a round that did not order the restructure.
  # An empty tree did not arrive in any shape, so it has nothing to preserve.
  #
  # This is the same probe, making the same mistake, that had to be taken out
  # of bootstrap_state: each_drop_asset answers about one corner, and over a
  # tree with no assets every answer it can give is the absence one. Fixing
  # that caller did not reach this one.
  if [[ "$state" == "cold" ]] || bootstrap_is_cdtempl_shaped "$target"; then
    bootstrap_contract_shaped "$state"
  else
    bootstrap_contract_asis
  fi

  bootstrap_contract_common
  return 0
}

bootstrap_contract_shaped() {
  local state="${1:-warm}"

  echo "## The shape to export"
  echo ""
  if [[ "$state" == "cold" ]]; then
    echo "Cdtempl owns exactly these paths under the target, and the tree is empty, so"
    echo "**this is the shape to build into** rather than one to preserve. What you"
    echo "export is unpacked into them:"
  else
    echo "Cdtempl owns exactly these paths under the target, and this tree is already in"
    echo "that shape. What you export is unpacked into them:"
  fi

  cat <<'EOF'

```
RETURN.md         this round's narrative -- what you did, what you could not do
index.md          manifest: every asset, its status, its spec version
brief.md          the order this round answers, if there was one
kit/              the neutral kit every artefact imports
assets/<slug>/    flat, one directory per asset
notes/            durable thinking that is not an asset
addenda/          REPO-AUTHORED. Never export this. See below
```

EOF
  return 0
}

bootstrap_contract_asis() {
  cat <<'EOF'
## What to export

**Export the tree in the shape it already has.** The same paths, reorganised
into nothing. This round's changes go in the files where they already live.

Cdtempl does have a target shape -- `assets/<slug>/`, `kit/`, `notes/`, a manifest
at `index.md` -- and **this document is not asking you to adopt it.** Converting
an as-is tree into it moves every file and breaks every relative pointer between
them. That is a round of its own, and if it is wanted you will be sent a brief
that says so and nothing else.

So a restructure nobody ordered arrives here as a tree that cannot be diffed
against the last one, which is the one thing storing the whole deliverable was
for.

EOF
  return 0
}

bootstrap_contract_common() {
  cat <<'EOF'
**Export the whole tree, always.** Not a delta, not the parts you changed. The
receiving side replaces what it has with what you send, so a partial export
reads as a deletion of everything you left out. This is why the whole tree is
the unit and not the round's diff.

**`addenda/` is not yours.** It is written by the receiving project to record a
gap in your delivery, in your voice, and it flows back to you. It retires when
one of your drops absorbs it. No install path will overwrite it, and an export
that carries an `addenda/` has it discarded with a message.

**`_inbox/` is not yours either.** It is where delivery archives are dropped off
on the receiving side. They are ephemeral transport, unpacked and then
irrelevant. Nothing you do concerns it.

**Nor are the project's own working documents.** Steel threads, work packages,
acceptance criteria -- anything whose home is the project's `intent/` directory.
You may be given them for a round, and you may draft new ones, but **they retire
from the drop once the project has taken them and must not survive more than one
round.** You can read the project's repository directly, so a copy you keep is
only a copy that drifts. If this round changed or authored any, say so in
`RETURN.md` file by file: installing the drop updates your copy and never
theirs, so anything you do not name is lost.

**Nor is this document, at any path.** `BOOTSTRAP-CD.md` is written by Cdtempl for
you and flows outward, and it is regenerated from the tree on every sync -- so a
copy you export back was already out of date when you sent it. It will have been
handed to you as an upload, which means it is probably sitting wherever your
uploads collect. **Delete it before you export**, along with any covering note
that came with it: those are transport, and transport that gets exported becomes
a permanent stale answer next to a live one.

**Nor is Cdtempl's own protocol material.** Whiteboard skeletons, `OUTBOX.md`,
node directories, anything describing how a drop is exchanged rather than what
the design is. A project using Cdtempl has exactly one concern, this tree, and
what it builds from it is its own business -- so samples and templates of the
protocol live in Cdtempl and never in a project's design system. If you are
holding any, delete it and say so in `RETURN.md`.

**Nor is `.gitignore`, at any depth.** It decides what the receiving repository
tracks, and the whole tree is tracked so the specification can be diffed against
the implementation. One arriving in a drop and saying `docs/` or `*.pdf` would
silently stop part of the deliverable being tracked, and nothing would report
it -- the tree would simply get smaller. So tracking policy flows from the
repository outward and never from a drop inward: any `.gitignore` in an export
is discarded on arrival, and named as it goes.

**Nor is `cdtempl.json`, at any depth.** It is the venture's own facts and order,
living at the tree root on the receiving side, and the order flows from the
venture to you -- never back. A copy arriving in an export would sit where the
next round reads its order from, so it is discarded on arrival the same way,
and named as it goes.

**Nor is `scratch/`, or any working directory of your own.** Sketches, trial
renders, screenshots taken to look at something once -- the material you make
*while* working rather than the material you deliver. An as-is export carries
everything, so it arrives here, and from that moment it is tracked, diffed and
read as deliverable by everyone downstream. If something in it turns out to
matter, **promote it to a real path and name it in `RETURN.md`**; otherwise leave
it out of the export.

## Two things this tree is not

**It is not code, and nothing runs on it.** It is specification: requirements and
information. Write it to be implemented, not to be executed.

**It is not hand-edited on the receiving side.** The one sanctioned exception is
`addenda/`. So if a document is wrong, it stays wrong until you fix it and
export again -- which is exactly why corrections have to land at source.

EOF
  return 0
}

# What the two version numbers on a spec.md mean.
#
# THE FIELD THAT WAS NEVER DEFINED ANYWHERE. It was asked for by name in the
# brief and read by name by `check`, and neither said what it counted -- so
# Claude Design supplied the only reading available to it, an asset revision
# counter, and bumped all sixteen of one drop's assets on the round that added
# classification. A reasonable reading of an undefined field. hv ruled on 31 July
# 2026 that it is the library's, and this section is that ruling landing where
# the reader who needs it will see it.
bootstrap_versions() {
  local target="$1"

  cat <<'EOF'
## The two version numbers, and what they count

**`spec_version` is not yours to increment.** It records **which version of the
specification the asset was built from** -- you copy the number the
specification carries and leave it alone. It is not a revision counter for the
asset, and a new draft of the same asset against the same specification carries
the same number as the last one.

That is what makes it useful: the receiving side compares your stamp against the
specification it holds, and a difference means one of you has moved. A number
each side increments on its own schedule cannot measure anything, because it
never disagrees for a reason.

**`kit_version` works the same way** for the design kit.

**So the asset's own progress is `status` and `coverage`, not a version.**
`spec-only`, `draft`, `partial` with what is covered, `complete`. That is where a
round's work shows up. If an asset changed and its `spec_version` did not, that
is correct and expected.

EOF

  bootstrap_version_numbers "$target"
  return 0
}

# The numbers themselves, which the section above explains and never stated.
#
# THE GAP THREE OF FOUR PROJECTS HIT ON THE SAME ROUND. On 31 July 2026 the
# section above shipped saying the stamp is copied from the specification -- and
# no document ever said what the specification's number was. Claude Design cannot
# read the library; it holds a drop. So snorkeltoast asked for the numbers by
# name, Lamplight left every stamp unset and said why, and Gyre & Gymble reset
# sixteen assets to 1 against a library holding two of them at 2. All three were
# reasoning correctly from a document that had withheld the one fact they needed.
#
# The instruction to copy a number is worthless without the number. This is the
# generator answering its own question at the point it asks it, because the
# alternative is a human relaying two integers per round forever.
#
# IT MUST ALSO ANSWER FOR AN ASSET THE LIBRARY DOES NOT HOLD, and that is the
# commoner case rather than the edge: of the four trees in round one, only Gyre &
# Gymble is built from taxonomy slugs at all. Lamplight's four assets are its own
# names, and two trees carry no `assets/` in the Cdtempl shape whatsoever. For those
# the honest number is no number, and saying so is what stops the next round
# inventing one -- which is exactly the misuse that made this section necessary.
bootstrap_version_numbers() {
  local target="$1"
  local slug library_spec version
  local rows="" unknown="" known=0 missing=0

  # `kit_version` is read from the library manifest and not from the per-spec
  # copies, because that is where `brief` reads it (cmd_brief.sh) and a document
  # that stamped a different number from the brief ordering the work would be the
  # two-lists-that-disagree defect this file already carries three warnings about.
  local kit_version
  kit_version="$(library_get kit_version)" || kit_version=""

  while IFS= read -r slug; do
    [[ -z "$slug" ]] && continue
    if library_spec="$(spec_path "$slug")"; then
      version="$(fm_get "$library_spec" spec_version)" || version=""
      if [[ -n "$version" ]]; then
        rows="$rows| \`$slug\` | $version |"$'\n'
        known=$((known + 1))
      else
        # A library entry with no version of its own. The drop cannot copy what
        # the library never stamped, and this is a fault in the library rather
        # than in the drop -- so it says so instead of printing a blank cell.
        rows="$rows| \`$slug\` | **the library entry carries none -- leave yours out** |"$'\n'
        known=$((known + 1))
      fi
    else
      unknown="$unknown\`$slug\`, "
      missing=$((missing + 1))
    fi
  done < <(each_drop_asset "$target")

  # The kit is taxonomy asset 20 and lives at the target root, so `each_drop_asset`
  # does not walk it -- the same reason `check` handles it by name after its loop.
  # It was the one asset Gyre & Gymble left unstamped, and the library holds a
  # version for it, so omitting it here would withhold the very number that round
  # went looking for.
  if drop_has_kit "$target"; then
    if library_spec="$(spec_path "kit")"; then
      version="$(fm_get "$library_spec" spec_version)" || version=""
      if [[ -n "$version" ]]; then
        rows="$rows| \`kit\` | $version |"$'\n'
        known=$((known + 1))
      fi
    fi
  fi

  echo "### The numbers, for this tree"
  echo ""

  if [[ "$known" -gt 0 ]]; then
    echo "**Copy these.** They are what the library holds today, and they are the whole"
    echo "answer to \"what do I stamp\" -- there is nothing to work out."
    echo ""
    echo "| Asset | \`spec_version\` |"
    echo "| ----- | -------------- |"
    printf '%s' "$rows"
    echo ""

    if [[ -n "$kit_version" ]]; then
      echo "**\`kit_version: $kit_version\`** on every one of them. It is one number for the whole"
      echo "library, not a number per asset."
      echo ""
    fi
  fi

  if [[ "$missing" -gt 0 ]]; then
    if [[ "$missing" -eq 1 ]]; then
      echo "**One asset here has no entry in the library: ${unknown%, }.**"
    else
      echo "**${missing} assets here have no entry in the library: ${unknown%, }.**"
    fi
    echo "There is no number to copy for them, so stamp **\`spec_version: unassigned\`**"
    echo "-- the literal word -- rather than inventing a value. It says the asset was"
    echo "built ahead of the library, which is a correct state and not a gap in your"
    echo "work; when the library gains an entry, the check will ask for a rebuild"
    echo "against it. A number you choose yourself is the revision counter this"
    echo "section exists to stop."
    echo ""
  fi

  if [[ "$known" -eq 0 && "$missing" -eq 0 ]]; then
    echo "**Nothing in this tree carries a copyable number.** There are no assets in the"
    echo "Cdtempl shape here, so there is no specification for anything to have been"
    echo "built from. Anything you deliver in that shape stamps **\`spec_version:"
    echo "unassigned\`** -- the literal word. Do not issue a number, and do not carry"
    echo "one forward from another project -- a number nobody issued cannot measure"
    echo "anything."
    echo ""
  fi

  return 0
}

# ADDING THE FIELD IS ONLY HALF THE SEPARATION, and this section shipped knowing
# only the first half. Three of the four projects in round one were adding
# classification for the first time and did the whole job, because a tree with no
# `classification` anywhere makes the instruction "declare it" complete.
#
# Gyre & Gymble was not. It already carried `classification` on all sixteen
# assets from an earlier round, and still carried `internal` in `audience` on
# eleven of them. Claude Design read a section that said declare this field, found
# the field declared, and correctly moved on -- so `check` reported the same
# eleven conflations before and after a pass that was doing exactly as it was told.
#
# Nothing here had ever said to take the value OUT of the other field. A rule that
# can only be satisfied by an instruction nobody wrote is a defect in the document,
# not in the supplier, and it would have stayed at eleven every round forever.
bootstrap_classification() {
  local only
  only="$(classification_only_prose)"

  cat <<'EOF'
## Classification, on every `spec.md`

An axis of its own, not a flavour of `audience`. Three values:

| Classification | Means |
| -------------- | ----- |
| `public` | May be shown externally |
| `internal` | Within the venture only |
| `confidential` | Internal **and** behind access control |

**It governs where material may be shown, never whether it is committed.**
Everything is stored regardless of classification. It is not a delivery filter
and must not be used as one -- do not omit an asset because it is confidential.

EOF

  cat <<EOF
**Once \`classification\` carries the value, take it out of \`audience\`.** Declaring
the new field is only half of separating the two axes -- leaving the same word in
the old one keeps them conflated in the exact place the conflation started.
\`audience\` answers **who a thing is for**: \`printer\`, \`developer\`, \`investor\`, a
named person. So \`audience: ["internal", "jen"]\` becomes \`audience: ["jen"]\`, and
the classification says the rest.

**\`public\` stays**, because it is a real answer to both questions -- the general
public genuinely is who a landing page is for, and that is independent of where
the page may be shown. Only $only reach \`audience\` by conflation.

**This applies to a tree that already carries \`classification\`.** If the field was
declared in an earlier round, the values may still be sitting in \`audience\` as
well; that is the common case rather than the exception, and it is the half of
the job most likely to be already half-done.

EOF
  return 0
}

# The addenda themselves, which is not the same as the files in the directory.
#
# `README.md` documents `addenda/` -- the filing protocol, what belongs there,
# how one retires. It is the receiving project talking to itself, not to Claude
# Design about a gap in a delivery. Counting it said "3 addenda" over Baize's
# two, and quoting it handed Claude Design a filing convention introduced as "a
# thing you got wrong or left out, in their words", to be absorbed and retired.
#
# One walker so the count and the quoting cannot disagree, which is the same
# mistake the skip lists above were making.
each_addendum() {
  find "$1/addenda" -type f -name '*.md' ! -name 'README.md' 2>/dev/null | sort
}

# Addenda the receiving project has written and no drop has yet absorbed.
#
# THE POINT OF THE WHOLE RETURN LEG. Canon says an addendum flows back to Claude
# Design and retires when a drop absorbs it -- it says THAT it flows back and
# never HOW, and until this nothing implemented it. The answer was a human
# carrying notes in ~/Downloads at midnight, which is where "corrections land at
# source" actually hurt.
bootstrap_addenda() {
  local target="$1"
  local file count

  if [[ ! -d "$target/addenda" ]]; then
    return 0
  fi

  count="$(each_addendum "$target" | grep -c . || true)"

  echo "## Addenda awaiting you"
  echo ""

  if [[ "$count" == "0" ]]; then
    echo "None waiting. \`addenda/\` exists and holds nothing for you."
    echo ""
    return 0
  fi

  echo "**$count addenda.** These were written by the receiving project to record a gap in a"
  echo "previous delivery. Each one is a thing you got wrong or left out, in their words."
  echo "**Absorb them into this round and they retire.** Ignore them and they will be here"
  echo "again next round, because nothing else retires them."
  echo ""

  while IFS= read -r file; do
    [[ -z "$file" ]] && continue
    echo "### \`$(basename "$file")\`"
    echo ""
    sed 's/^/> /' "$file"
    echo ""
  done < <(each_addendum "$target")

  return 0
}

# The step list only names steps this document actually set up.
#
# It told every reader to "absorb any addenda listed above" including the three
# of four projects with no `addenda/` at all, so the step pointed at a section
# that was not there. Small, but this document's whole authority is that it
# describes what is actually present, and an instruction referring to something
# absent spends that authority for nothing.
bootstrap_next() {
  local state="$1"
  local target="${2:-}"
  local n=1

  echo "## What to do now"
  echo ""

  if [[ "$state" == "cold" ]]; then
    echo "$((n++)). Build the design system into the shape above."
    echo "$((n++)). Give every asset a \`spec.md\` carrying its \`classification\`."
    echo "$((n++)). Write \`index.md\` as the manifest and \`RETURN.md\` as the narrative."
    echo "$((n++)). Export **the whole tree** as one archive."
  else
    echo "$((n++)). Read the inventory above. **That is the current state** -- do not rebuild"
    echo "   what is already there."
    if [[ -n "$target" ]] && [[ -n "$(each_addendum "$target")" ]]; then
      echo "$((n++)). Absorb the addenda above; they retire when you do."
    fi
    echo "$((n++)). Do this round's work."
    echo "$((n++)). Export **the whole tree** as one archive, including everything you did"
    echo "   not touch."
  fi

  cat <<'EOF'

Where you lack a fact, say so in `RETURN.md` rather than inventing one. A stated
gap is information; an invented fact is a defect that survives several rounds
before anyone catches it.
EOF

  echo ""
  return 0
}

# ============================================================================
# THE DELTA
# ============================================================================

# What changed on the repository side since the last export, for a WARM round.
#
# The inbound leg was tooled from the start -- archive into `_inbox/`, cdtempl
# unpacks it. The outbound leg was a human carrying notes. This is that leg: the
# same tree scan, narrowed to what a long-running Claude Design project does not
# already know, so a warm round does not have to re-read the whole bootstrap.
compose_delta() {
  local target="$1"

  echo "# Since your last export"
  echo ""
  echo "**For the Claude Design project that already holds this design system.** Generated by"
  echo "\`cdtempl bootstrap --delta\` from the tree. If you are a fresh project rather than a"
  echo "resuming one, read \`BOOTSTRAP-CD.md\` instead -- it carries everything, this carries"
  echo "only what changed."
  echo ""

  bootstrap_addenda "$target"
  brief_numbering "$target"

  echo "## Then"
  echo ""
  echo "Do the round, absorb the addenda above, and export **the whole tree** -- not a delta."
  echo "The receiving side replaces what it holds with what you send, so anything you leave"
  echo "out reads as a deletion."
  echo ""

  return 0
}
