#!/usr/bin/env bash
#
# cdtempl site - stand up the microsite over the target
#
# Independent of the application the designs relate to, and knows nothing about
# Phoenix, Ash or Laksa. It serves what is in the target and no more. That
# confinement is what lets the microsite stay independent of the application it
# describes -- the target is the as-designed record, and this is a window onto
# it, not onto the build.
#
# It generates into $CDTEMPL_TARGET/site/, which is deliberately NOT one of the
# paths a drop owns. That is the whole reason the owned-path list exists: a
# generated site sitting in the target survives the next drop instead of being
# deleted by it.
#
# The generated page declares itself generated in a comment on line one, so it is
# exempt from the colour check by the same declaration rule every vendored
# runtime uses. Nothing here is a special case.
#

CDTEMPL_SITE_PORT_DEFAULT="8080"

cmd_site() {
  local flag_target=""
  local port="$CDTEMPL_SITE_PORT_DEFAULT"
  local serve=1

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --target)
        if [[ -z "${2:-}" ]]; then
          error "--target requires a path"
          return 2
        fi
        flag_target="$2"
        shift 2
        ;;
      --port)
        if [[ -z "${2:-}" ]]; then
          error "--port requires a number"
          return 2
        fi
        port="$2"
        shift 2
        ;;
      --build)
        serve=0
        shift
        ;;
      -h|--help)
        show_help site
        return 0
        ;;
      *)
        error "unknown option: $1"
        return 2
        ;;
    esac
  done

  local target source
  target="$(resolve_target "$flag_target" "$PWD")" || return 2
  source="$(target_source "$flag_target" "$PWD")" || return 2

  describe_target "$target" "$source" "$PWD"
  echo ""

  if ! drop_looks_valid "$target"; then
    error "no drop at $target -- expected assets/ or kit/ underneath it"
    return 2
  fi

  mkdir -p "$target/site" || {
    error "could not create $target/site"
    return 1
  }

  build_site "$target" | atomic_write "$target/site/index.html" || return 1
  success "site built at $target/site/index.html"

  if [[ "$serve" -eq 0 ]]; then
    return 0
  fi

  serve_site "$target" "$port"
}

# ============================================================================
# BUILD
# ============================================================================

build_site() {
  local target="$1"
  local venture round

  venture="$(fm_get "$target/index.md" venture 2>/dev/null || basename "$target")"
  round="$(fm_get "$target/index.md" round 2>/dev/null || echo '')"

  echo "<!-- @generated by cdtempl site. Do not edit; rebuild with 'cdtempl site'. -->"
  echo "<!doctype html>"
  echo "<html lang=\"en\"><head>"
  echo "<meta charset=\"utf-8\">"
  echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
  echo "<title>$venture -- design record</title>"
  site_style
  echo "</head><body>"
  echo "<main>"

  echo "<header>"
  echo "<h1>$venture</h1>"
  if [[ -n "$round" ]]; then
    echo "<p class=\"meta\">Round $round &middot; the as-designed record</p>"
  else
    echo "<p class=\"meta\">the as-designed record</p>"
  fi
  echo "<p class=\"note\">This is what was <em>designed</em>. The application holds what"
  echo "was <em>built</em>. Keeping them apart is the point: you can hold one against"
  echo "the other and see where implementation diverged from intent.</p>"
  echo "</header>"

  site_documents "$target"
  site_assets "$target"
  site_notes "$target"

  echo "</main>"
  echo "</body></html>"
}

# Greyscale only, and every value is a kit ramp step. The site describes a
# deliberately neutral kit, so a site with a brand colour in it would be
# arguing against its own content.
site_style() {
  cat <<'CSS'
<style>
  :root {
    --grey-0: #ffffff; --grey-50: #f7f7f7; --grey-100: #ededed;
    --grey-300: #c4c4c4; --grey-600: #616161; --grey-700: #474747;
    --grey-900: #1a1a1a;
    --line: var(--grey-300);
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--grey-0); color: var(--grey-900);
    font: 400 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }
  main { max-width: 62rem; margin: 0 auto; padding: 48px 24px 96px; }
  header { border-bottom: 1px solid var(--line); padding-bottom: 24px; margin-bottom: 48px; }
  h1 { font-size: 39px; font-weight: 600; margin: 0 0 8px; }
  h2 { font-size: 25px; font-weight: 600; margin: 48px 0 16px; }
  .meta { color: var(--grey-600); margin: 0 0 16px; font-size: 13px;
          font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
  .note { color: var(--grey-700); max-width: 68ch; margin: 0; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid var(--line);
           vertical-align: top; }
  th { font-weight: 600; color: var(--grey-600); text-transform: lowercase; }
  tbody tr:hover { background: var(--grey-50); }
  code, .mono { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13px; }
  a { color: var(--grey-900); text-decoration: underline; text-underline-offset: 2px; }
  a:hover { color: var(--grey-600); }
  ul { padding-left: 20px; }
  .num { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; color: var(--grey-600); }
  .empty { color: var(--grey-600); font-style: italic; }
  .badge { display: inline-block; padding: 1px 6px; border: 1px solid var(--line);
           background: var(--grey-100); color: var(--grey-700); font-size: 13px;
           font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
  @media (max-width: 40rem) {
    main { padding: 24px 16px 64px; }
    table { display: block; overflow-x: auto; }
  }
</style>
CSS
}

site_documents() {
  local target="$1"
  local file any=0

  echo "<h2>Documents</h2>"
  echo "<ul>"
  for file in RETURN.md brief.md index.md; do
    if [[ -f "$target/$file" ]]; then
      echo "<li><a href=\"../$file\"><code>$file</code></a></li>"
      any=1
    fi
  done
  if [[ -f "$target/kit/kit.md" ]]; then
    echo "<li><a href=\"../kit/kit.md\"><code>kit/kit.md</code></a> -- the neutral kit every artefact imports</li>"
    any=1
  fi
  if [[ "$any" -eq 0 ]]; then
    echo "<li class=\"empty\">none yet</li>"
  fi
  echo "</ul>"
}

site_assets() {
  local target="$1"
  local slug spec dir count=0

  echo "<h2>Assets</h2>"
  echo "<table>"
  echo "<thead><tr><th>slug</th><th>name</th><th>form</th><th>status</th>"
  echo "<th>blanks</th><th>coverage</th><th>artefacts</th></tr></thead>"
  echo "<tbody>"

  while IFS= read -r slug; do
    if [[ -z "$slug" ]]; then continue; fi
    dir="$(drop_asset_dir "$target" "$slug")"

    echo "<tr>"
    echo "<td><code>$slug</code></td>"

    if spec="$(drop_spec_path "$target" "$slug")"; then
      echo "<td>$(fm_get "$spec" name || echo "$slug")</td>"
      echo "<td>$(fm_get "$spec" form || echo '&mdash;')</td>"
      echo "<td><span class=\"badge\">$(fm_get "$spec" status || echo '?')</span></td>"
      echo "<td class=\"num\">$(fm_get "$spec" blanks || echo '&mdash;') / $(fm_get "$spec" blanks_unique || echo '&mdash;')</td>"
      echo "<td class=\"num\">$(fm_get "$spec" coverage || echo '&mdash;')</td>"
    else
      echo "<td colspan=\"5\" class=\"empty\">no spec.md</td>"
    fi

    echo "<td>"
    site_artefact_links "$target" "$slug" "$dir"
    echo "</td>"
    echo "</tr>"
    count=$((count + 1))
  done < <(each_drop_asset "$target")

  if [[ "$count" -eq 0 ]]; then
    echo "<tr><td colspan=\"7\" class=\"empty\">no assets yet</td></tr>"
  fi

  echo "</tbody></table>"
}

site_artefact_links() {
  local target="$1"
  local slug="$2"
  local dir="$3"
  local file name any=0

  while IFS= read -r file; do
    if [[ -z "$file" ]]; then continue; fi
    name="$(basename "$file")"
    # The path is URL-encoded only for spaces, which is the one character the
    # built artefacts actually use. Anything more would need a real encoder, and
    # a filename needing one is a signal about the filename.
    echo "<a href=\"../assets/$slug/${name// /%20}\">$name</a><br>"
    any=1
  done < <(each_artefact_file "$dir")

  if [[ "$any" -eq 0 ]]; then
    echo "<span class=\"empty\">spec only</span>"
  fi
}

site_notes() {
  local target="$1"
  local file any=0

  if [[ ! -d "$target/notes" ]]; then
    return 0
  fi

  echo "<h2>Notes</h2>"
  echo "<p class=\"note\">Durable thinking that is not an asset.</p>"
  echo "<ul>"
  while IFS= read -r file; do
    if [[ -z "$file" ]]; then continue; fi
    echo "<li><a href=\"../notes/$(basename "$file")\">$(basename "$file")</a></li>"
    any=1
  done < <(find "$target/notes" -maxdepth 1 -type f -name '*.md' 2>/dev/null | sort)
  if [[ "$any" -eq 0 ]]; then
    echo "<li class=\"empty\">none</li>"
  fi
  echo "</ul>"
}

# ============================================================================
# SERVE
# ============================================================================

# Rooted at the target, not at site/, so the relative links from the generated
# page out to ../assets/<slug>/ resolve. A server rooted at site/ would render
# the index and then 404 every artefact on it.
serve_site() {
  local target="$1"
  local port="$2"

  require_command python3 "pre-installed on macOS" || return 1

  info "serving $target on http://localhost:$port/site/"
  info "ctrl-c to stop"
  echo ""

  python3 -m http.server "$port" --directory "$target"
}
