#!/usr/bin/env bash
#
# cdsync - the shape of a drop
#
# What Claude Design owns inside the target, and how to walk it. `import`,
# `check` and `site` all read a drop, and all three read it through here.
#
# The owned-path list below is the single most safety-critical constant in the
# tool. It has exactly one definition for that reason.
#

# ============================================================================
# WHAT CLAUDE DESIGN OWNS
# ============================================================================

# The only paths `cdsync import` may write inside the target.
#
# Learned the hard way. A drop arrived without templprj/README.md -- the only
# statement anywhere in that directory of why the placeholder must be boring --
# and syncing the drop over the target deleted it silently. Nothing removed it
# deliberately; the drop is simply the whole directory, so anything present in
# the target and absent from the drop went with it.
#
# brief.md survives that today only because Claude Design echoes it back
# verbatim, which is a convention propping up a guarantee, and conventions do not
# hold. So the boundary is explicit instead: these paths and nothing else.
#
# It is the same as-designed versus as-built separation the whole design rests
# on, applied one level down. A venture can keep its own files in the target --
# and cdsync can generate site/ there -- without a later drop eating them.
CDSYNC_DROP_OWNED_DIRS="assets kit notes"
CDSYNC_DROP_OWNED_FILES="index.md RETURN.md"

# Does this directory hold drop content, rather than merely wrap it?
#
# The unwrap in stage_drop needs a floor. Descending through a wrapper is safe
# only while the thing being descended through IS a wrapper; the moment a
# directory names something the drop contract owns, that directory is the drop
# root and going deeper would hand back one of its subtrees.
#
# Asks the owned lists rather than carrying its own idea of the shape, so a
# drop root is defined in exactly one place. The alternative -- "a wrapper has
# one child" and nothing more -- cannot tell a two-deep wrapper from a drop
# that shipped `assets/` alone, and would silently descend into the assets.
drop_root_is_shaped() {
  local dir="$1"
  local owned

  for owned in $CDSYNC_DROP_OWNED_DIRS $CDSYNC_DROP_OWNED_FILES; do
    if [[ -e "$dir/$owned" ]]; then
      return 0
    fi
  done

  return 1
}

# Repo-authored material inside the target that NO install path may overwrite.
#
# `addenda/` is written by the project, about the design, where the design has a
# gap -- copy for states the design corpus does not carry, and the like. It is the
# one thing under the target that does NOT arrive from an export: it is authored
# here and flows BACK to Claude Design, and it retires when a drop absorbs it.
#
# `import` already honours this, because it writes only the owned paths above and
# leaves everything else standing. The hazard is the OTHER install path. An as-is
# dump is unzipped over the tree wholesale -- because `import` writes five paths
# and would discard most of such a dump -- and that replace destroys anything
# hand-added, silently. Baize lost a handoff file and eight ADR banners to exactly
# that on 30 July 2026, between its 09:49 and 16:29 drops, and noticed only by
# seeing the files were gone.
#
# So the two install paths have opposite failure modes and there is no third:
# `import` protects addenda and discards an as-is dump; a hand replace preserves
# the dump and destroys addenda. Declared here so the boundary is stated once, in
# the module that owns the drop contract, rather than being re-derived by whoever
# writes the next brief.
# Two entries, and they are protected for opposite reasons.
#
# `addenda/` is written BY the receiving project ABOUT the drop, and flows back
# to Claude Design to retire when a later drop absorbs it. `BOOTSTRAP-CD.md` is
# written by Cdsync FOR Claude Design, and is regenerated by every sync so its
# currency is continuous while its use stays rare. Both are Cdsync-side output
# living inside a tree Claude Design replaces wholesale, so without this
# declaration an export silently eats them.
#
# Named PATHS rather than DIRS because the guard was always on names: the replace
# loop walks every top-level entry and asks about the basename, so a file is
# protected exactly as a directory is. It was called DIRS while it held only one
# entry and that entry was a directory.
CDSYNC_DROP_PROTECTED_PATHS="addenda BOOTSTRAP-CD.md"

# Is this top-level name one no install path may overwrite?
#
# THE reader of the declaration above. It had none for a day: `import` protected
# addenda/ only because its owned list happened not to mention it, which is
# emergence rather than enforcement -- add one name to CDSYNC_DROP_OWNED_DIRS and
# the protection disappears with nothing to say so. Both install paths ask here
# now, so the declaration decides rather than describes.
# Files a drop may not deliver, at any depth, because the REPOSITORY owns what
# they decide and a drop is not entitled to a say.
#
# `.gitignore` decides what is tracked, and the whole reason design/system/ is
# tracked is so the specification can be diffed against the implementation. A
# drop-carried .gitignore is therefore uncontrolled input that can change what
# the repository records about itself: one saying `docs/` or `*.pdf` would
# silently stop part of the deliverable being tracked, and nothing would report
# it -- the tree would simply get smaller.
#
# Today's drops ship one saying `_inbox/`, which agrees with the repo-owned
# `design/.gitignore` and is harmless. That agreement is the accident, not the
# design. It is also not reliable: Lamplight's 2026-07-31 export shipped no
# .gitignore at all, and Baize had deleted its repo-owned guard the day before
# on the reasoning that the drop's copy made it redundant.
#
# So the rule is direction, not content: tracking policy flows from the repo
# outward and never from a drop inward. This is the mirror of
# CDSYNC_DROP_PROTECTED_PATHS -- that declares what a drop may not overwrite,
# this declares what a drop may not deliver.
CDSYNC_DROP_REFUSED_FILES=".gitignore"

# Is this basename one no drop may deliver?
drop_file_is_refused() {
  local name="$1"
  local known

  for known in $CDSYNC_DROP_REFUSED_FILES; do
    if [[ "$name" == "$known" ]]; then
      return 0
    fi
  done

  return 1
}

# Remove every refused file from a STAGED tree, printing one line each.
#
# Operates on the staging copy rather than filtering during the write, so it
# catches every depth with one sweep and both install paths get the same
# behaviour from the same code. Printing matters as much as removing: a drop
# quietly losing a file it shipped is the kind of silent divergence that gets
# discovered three rounds later.
drop_strip_refused() {
  local staged="$1"
  local file name known stripped=0

  if [[ ! -d "$staged" ]]; then
    return 0
  fi

  for known in $CDSYNC_DROP_REFUSED_FILES; do
    while IFS= read -r file; do
      [[ -n "$file" ]] || continue
      name="${file#"$staged"/}"
      rm -f "$file" || {
        error "could not discard $name from the staged drop"
        return 1
      }
      echo "discard  $name  (the repository owns tracking policy, not the drop)"
      stripped=$((stripped + 1))
    done < <(find "$staged" -type f -name "$known" 2>/dev/null)
  done

  return 0
}

drop_path_is_protected() {
  local name="$1"
  local known

  for known in $CDSYNC_DROP_PROTECTED_PATHS; do
    if [[ "$name" == "$known" ]]; then
      return 0
    fi
  done

  return 1
}

# Any name declared both owned and protected, one per line.
#
# The two lists say opposite things -- "Claude Design writes this" and "no
# install path may write this" -- so a name in both is a contract that cannot be
# satisfied. Whichever way the code happened to resolve it would be an accident
# of ordering, and the losing case is repo-authored work overwritten silently.
# Better to refuse to install at all than to pick.
drop_contract_conflicts() {
  local owned

  for owned in $CDSYNC_DROP_OWNED_DIRS $CDSYNC_DROP_OWNED_FILES; do
    if drop_path_is_protected "$owned"; then
      echo "$owned"
    fi
  done

  return 0
}

# Refuse to write anything while the contract contradicts itself. Called by both
# install paths, which are the only two places the contradiction has teeth.
drop_guard_contract() {
  local conflicts

  conflicts="$(drop_contract_conflicts)"

  if [[ -z "$conflicts" ]]; then
    return 0
  fi

  error "the drop contract contradicts itself"
  echo "" >&2
  printf '%s\n' "$conflicts" | sed 's/^/    /' >&2
  echo "" >&2
  echo "  Each name above is declared BOTH owned by Claude Design and protected" >&2
  echo "  from every install path. Those cannot both hold. Resolve it in" >&2
  echo "  lib/drop.sh rather than letting the order of two loops decide which" >&2
  echo "  wins -- the losing case is repo-authored work overwritten in silence." >&2
  return 1
}

# ============================================================================
# WALKING A DROP
# ============================================================================

# Emit every asset slug present in a drop, one per line.
#
# THE walker of a drop's assets/. Consume it with process substitution, never a
# pipe -- a pipe subshells the loop body and discards whatever the body
# accumulates, so the caller reports nothing and reports it successfully.
#
# `kit` is deliberately absent: it is taxonomy asset 20 and it lives at the
# target root rather than under assets/, because it is the one thing every other
# asset imports. Callers that want it ask for it by name -- see drop_has_kit.
each_drop_asset() {
  local root="$1"
  local dir slug

  if [[ ! -d "$root/assets" ]]; then
    return 0
  fi

  for dir in "$root"/assets/*/; do
    if [[ ! -d "$dir" ]]; then continue; fi
    slug="$(basename "$dir")"
    case "$slug" in
      _*|.*) continue ;;
    esac
    echo "$slug"
  done

  return 0
}

drop_asset_dir() {
  echo "$1/assets/$2"
}

drop_spec_path() {
  local root="$1"
  local slug="$2"
  local path

  if [[ "$slug" == "kit" ]]; then
    path="$root/kit/kit.md"
  else
    path="$root/assets/$slug/spec.md"
  fi

  if [[ ! -f "$path" ]]; then
    return 1
  fi

  echo "$path"
}

drop_has_kit() {
  [[ -d "$1/kit" ]]
}

drop_tokens_path() {
  local tokens="$1/kit/tokens.json"

  if [[ ! -f "$tokens" ]]; then
    return 1
  fi

  echo "$tokens"
}

# Does this directory look like a drop at all?
#
# Checked before anything walks it, so `cdsync check` run in the wrong place says
# so rather than reporting a clean bill of health for an empty directory. A
# silent pass on nothing is the worst possible output for a checker.
drop_looks_valid() {
  local root="$1"

  [[ -d "$root" ]] && { [[ -d "$root/assets" ]] || [[ -d "$root/kit" ]]; }
}
